load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

cc_binary(
    name = "RuleofSarrus_test",
    srcs = ["RuleofSarrus_test.cc"],
    deps = ["//lib:RuleofSarrus",
    "@com_google_googletest//:gtest_main"
    ],
)